# Vagrantfile for setting up a Yocto build environment

Vagrant.configure("2") do |config|
  # Base box
  config.vm.box = "alvistack/ubuntu-22.04"

  # VM settings
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
    vb.cpus = 4
  end


  # Add access to USB of host
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--usbehci", "on"]
	vb.customize ["modifyvm", :id, "--usbxhci", "on"]	
	vb.customize ["modifyvm", :id, "--usbcardreader", "on"]		
  end


  # Networking
  config.vm.network "private_network", ip: "192.168.33.12"

  # Sync folder between host and guest (optional)
  # config.vm.synced_folder "./yocto-project", "/home/vagrant/yocto-project"

  # Provisioning script
  config.vm.provision "shell", inline: <<-SHELL
    # Update the package list
    sudo apt-get update

    # Install required packages for Yocto
    sudo apt install -y gawk wget git diffstat unzip texinfo \
      gcc build-essential chrpath socat cpio python3 \
      python3-pip python3-pexpect xz-utils debianutils \
      iputils-ping python3-git python3-jinja2 python3-subunit \
      zstd liblz4-tool file locales libacl1 xterm
        
	sudo locale-gen en_US.UTF-8
    
	# Install bmap tool to flash sd cards
	sudo apt install -y bmap-tools 

  SHELL

  # SSH access
  config.ssh.insert_key = false  
end
