# Vagrantfile for setting up a Yocto build environment

Vagrant.configure("2") do |config|
  # Base box
  config.vm.box = "ubuntu/jammy64"
  config.vm.boot_timeout = 600
  
  # Specify the disk size (in GB)
  config.disksize.size = "100GB"
  
  # VM settings
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
    vb.cpus = 4
  end
  
  

  # Add access to USB of host
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--usbehci", "on"]
	vb.customize ["modifyvm", :id, "--usbxhci", "on"]	
	vb.customize ["modifyvm", :id, "--usbcardreader", "on"]		
  end


  # Networking
  config.vm.network "private_network", ip: "192.168.33.12"
    
  # Sync folder between host and guest (optional)
  # config.vm.synced_folder "./yocto-project", "/home/vagrant/yocto-project"

  # Provisioning script
  config.vm.provision "shell", inline: <<-SHELL
    # Update the package list
    sudo apt-get update

    # Install required packages for Yocto Dunfell		
	sudo apt-get install -y gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential \
	 chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping \
	 python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev pylint xterm python3-subunit mesa-common-dev

	# Install cmake
	sudo apt-get install -y cmake
	
  SHELL

  # SSH access
  config.ssh.insert_key = false  
end
